spring:
  application:
    name: Unexpected_Stories_Back_V2

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  logging:
    level:
      org:
        hibernate:
          SQL: debug
          type: trace

  security:
      oauth2:
        client:
          registration:
            naver:
              client-name: naver
              client-id: ${CLIENT_ID}
              client-secret: ${CLIENT_SECRET}
              redirect-uri: http://localhost:8080/login/oauth2/code/naver
              authorization-grant-type: authorization_code
              scope:
                - name
                - email
          provider:
            naver:
              authorization-uri: https://nid.naver.com/oauth2.0/authorize
              token-uri: https://nid.naver.com/oauth2.0/token
              user-info-uri: https://openapi.naver.com/v1/nid/me
              user-name-attribute: response